### ISSUE TITLE
make polarPoint more fp-like

### ISSUE THREAD

**Issue by justin-hackin** [justin-hackin/fp-ts-svg-path-d#1]
function location: https://github.com/justin-hackin/fp-ts-svg-path-d/blob/7dfbb4ab4d14326cfaafd7ac2523514812304ec2/src/lib/geom.ts#L56

Failed attempt: 

```ts
type NumberTransformer = (arg0: number)=>number;
type CoordinatesTransformer = [NumberTransformer, NumberTransformer];
export const polarPoint = (radius: number) => (circleFraction: number) :Point2D => (
  fpFunc.pipe([Math.cos, Math.sin] as CoordinatesTransformer,
    array.ap(circleFraction * TWO_PI - TWO_PI / 4),
    array.map((num) => num * radius))
);
```

**Comment by vinassefranche** [comment]
If you really want to use ap, I think you need to 'reverse' how you do it, like:
```typescript
export const polarPoint = (radius: number) => (circleFraction: number) =>
  pipe(
    [
      (transformer: NumberTransformer) =>
        transformer(circleFraction * TWO_PI - TWO_PI / 4),
    ],
    array.ap([Math.cos, Math.sin]),
    array.map(num => num * radius),
  );
```

If I were you, I'd something something simpler like:
```typescript
export const polarPoint = (radius: number) => (circleFraction: number) =>
  pipe(
    [Math.cos, Math.sin] as CoordinatesTransformer,
    array.map(
      transformer => transformer(circleFraction * TWO_PI - TWO_PI / 4) * radius,
    ),
  );

```

**Comment by justin-hackin** [comment]
Thanks @vinassefranche for helping me understand array apply. My only point of reference for apply was in the TaskEither context from https://cjonas.gitbook.io/mostly-adequate-fp-ts/chapter-10-applicative-functors

Adapted here to Either
```
const renderPage = (destinations: string) => (events: string) => `<div>${destinations}${events}<div>`;

fpFunc.pipe(
  either.right(renderPage),
  either.ap(either.right('destination')),
  either.ap(either.right('events')),
  either.getOrElse(() => 'none'),
  console.log,
);
```

It looks like array apply is very different and doesn't have the same analogous behaviour of a map between either/array context. Now that I see this, I agree the apply syntax is overkill. Unfortunately your solution still suffers from the problem that the return type of my function needs to be `[number, number]` but this returns `number[]`.

**Comment by vinassefranche** [comment]
I just discovered `ReadonlyTuple` that could help here:
```typescript
type NumberTransformer = (arg0: number)=>number;
export const polarPoint = (radius: number) => (circleFraction: number) => {
  const foo = (transformer: NumberTransformer) => transformer(circleFraction * TWO_PI - TWO_PI / 4) * radius;
  return pipe(
    [Math.cos, Math.sin],
    ReadonlyTuple.bimap(
      foo,
      foo,
    ),
  );
}
```
It's not 100% clean as you need to put `foo` twice but it looks good enough to me and you have the correct output type.

**Comment by justin-hackin** [comment]
@vinassefranche ooh, that's a good learning tidbit there with ReadonlyTuple.bimap, thanks! I actually decided to use object notation because of this hence closing. I'm going to deliberate if I should switch back to array because now I need to always rely on casting function so I can use the more ergonomic square bracket syntax.
